on:
  push:
    tags:        
      - v0.0.0
  workflow_dispatch:
name: Create a list of issues
permissions:
  contents: read
  issues: write 
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/template-actions/
        with:
          action: create-issues
          myToken: ${{ secrets.GITHUB_TOKEN }}
