name: Issues to Readme
permissions:
  contents: write
  issues: read
on:
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  issue2readme:
    runs-on: ubuntu-latest
    name: Transfer issue posts to a section of the front-page
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          action: issue-to-readme
